config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  devise_for :users
  resources :users

  resources :padraos

  get "welcome/index"

  resources :solexames do
    member do
      # /agreements/:id/export
      get 'export'
    end
  end

  resources :clilabs
  resources :exames
  resources :medicamentos do
    get :autocomplete_medicamento_descricao, :on => :collection
  end
  resources :viaaplics
  #resources :pacientes, :has_many => :receitas 
  resources :pacientes do
    resources :receitas 
  end
  resources :receitas do
    resources :receitais
  end

  resources :impreceita
  resources :impsolexame

  root 'welcome#index'

end

app/models/paciente.rb
class Paciente < ActiveRecord::Base
  has_many :receitas
  has_many :solexames

  cattr_reader :per_page
  @@per_page = 20

  validates_presence_of :nm_paciente, :dt_prim_consulta

  include FuncoesData

  def idade
    inoIdade(dt_nascimento) unless dt_nascimento.nil?
  end

  before_create do
    self.dt_prim_consulta = Date.today if dt_prim_consulta.blank?
  end

  before_update do
    self.dt_ult_consulta = Date.today
  end

end

app/controllers/pacientes_controller.rb
class PacientesController < ApplicationController

  before_filter :ler_estados_civis
  before_filter :ler_cidades

  before_action :set_paciente, only: [:show, :edit, :update, :destroy]

  add_breadcrumb "Home" , :root_path
  add_breadcrumb "Pacientes", :pacientes_path

  # controller
  #def auto_complete_for_paciente_cidade
  #  auto_complete_responder_for_cidade params[:paciente][:cidade]
  #end

  # GET /pacientes
  # GET /pacientes.xml
  def index
    #byebug
    condicao ="id > 0"
    unless params[:paciente_filtro].nil?
      filtro = params[:paciente_filtro].gsub(/[ ]/, '%')
      condicao += " and nm_paciente  ilike   '#{filtro}%'"
    end

    @totalpacientes = Paciente.count
    @pacientes = Paciente.paginate(:page => params[:page])
                         .where(condicao)
                         .order(:nm_paciente)
#                        .order(dt_ult_consulta: :desc)
  end

  # GET /pacientes/1
  # GET /pacientes/1.xml
  def show
    add_breadcrumb "show", pacientes_path, :title => "Volta para o index"
  end

  # GET /pacientes/new
  # GET /pacientes/new.xml
  def new
    @paciente = Paciente.new(dt_prim_consulta: Date.today)
    add_breadcrumb "novo", pacientes_path, :title => "Volta para o index"
  end

  # GET /pacientes/1/edit
  def edit
    add_breadcrumb "edit", pacientes_path, :title => "Volta para o index"
  end

  # POST /pacientes
  # POST /pacientes.xml
  def create
    @paciente = Paciente.new(paciente_params)

    respond_to do |format|
      if @paciente.save
        flash[:notice] = 'Paciente was successfully created.'
        format.html { redirect_to(@paciente) }
        format.json  { render action: 'show', :status => :created, :location => @paciente }
      else
        format.html { render :action => "new" }
        format.xml  { render :json => @paciente.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pacientes/1
  # PUT /pacientes/1.xml
  def update
    respond_to do |format|
      if @paciente.update(paciente_params)
        format.html { redirect_to @paciente, notice: 'Paciente alterado.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pacientes/1
  # DELETE /pacientes/1.xml
  def destroy
    @paciente.destroy
    respond_to do |format|
      format.html { redirect_to pacientes_url }
      format.json { head :no_content }
    end
  end

  def idade
    unless params[:dt_nascimento].blank?
      if params[:dt_nascimento].length > 9
       render :text => 'Idade: ' + inoIdade(params[:dt_nascimento])
      else
       render :text => 'Data incompleta'
      end
    end
  end

  protected

  def ler_estados_civis
    @aux = %w(Solteiro Casado Viuvo Amasiado)
    @estado_civis = @aux
  end

  def ler_cidades
    @cidades = Padrao.select('valores').where(['LOWER(campo) = ? ', 'cidade' ]).first
  end

  private
  def auto_complete_responder_for_cidade(value)

    # pega caracteres de fim de linha
    fimLinha = 13.chr+10.chr
    cadaLinha = @cidades.valores.split(fimLinha)

    @cidadefiltro = []
    for s in cadaLinha.grep(/#{value}/) # navega em cada linha que contem o digitado
      @cidadefiltro << Padrao.new(:valores=>s)
    end

    debugger
    render :inline => "<%= auto_complete_result(@cidadefiltro, 'valores') %>"
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_paciente
      @paciente = Paciente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paciente_params
      #params[:paciente]
      params.require(:paciente).permit(:nm_paciente, :dt_nascimento, :estado_civil, :endereco, :cidade,
        :profissao, :fone_casa, :e_mail, :dt_prim_consulta, :situacao, :encaminhado_por, :obs1, :obs2, :obs3, :obs4, :obs5,
        :antec_pai, :antec_mae, :antec_irmaos, :antec_conjuge, :antec_filhos)
    end

end

app/views/pacientes/_form.html.erb
      <%= simple_form_for @paciente, html: { class: 'form-horizontal' },
        wrapper: :horizontal_form,
        wrapper_mappings: {
          check_boxes: :horizontal_radio_and_checkboxes,
          radio_buttons: :horizontal_radio_and_checkboxes,
          file: :horizontal_file_input,
          boolean: :horizontal_boolean,
          datetime: :horizontal_multi_select,
          date: :horizontal_multi_select,
          time: :horizontal_multi_select
        } do |f| %>

      <fieldset class='caixa'>
        <legend class='caixa'>Paciente</legend>

        <%= f.input :nm_paciente, label: 'Nome'  %>

        <%= f.input :dt_nascimento, format: :default, label: 'Data nascimento', html5: true, wrapper: :small,  input_html: { :onblur => 'mostra_idade(this)' } %>

        <%= f.input :estado_civil, as: :select, collection: @estado_civis %>
        <%= f.input :endereco, label: 'Endereço' %>
        <%= f.input :cidade %>
        <%= f.input :profissao, label: 'Profissão' %>
        <%= f.input :fone_casa, label: 'Fone' %>
        <%= f.input :e_mail, label: 'Natural' %>
        <%= f.input :dt_prim_consulta, label: '1a. Consulta', html5: true %>
        <%= f.input :situacao %>
        <%= f.input :encaminhado_por %>

        <fieldset class='caixa'>
          <legend class='caixa'>Anamnese</legend>
          <%= f.input :obs1, label: 'Q.P./H.P.M.A.', input_html: { :rows => '3' }  %>
          <%= f.input :obs2, label: 'A.P./I.D.',     input_html: { :rows => '3' } %>

          <fieldset>
            <legend>Antecedentes Familiares</legend>
            <%= f.input :antec_pai, label: 'Pai' %>
            <%= f.input :antec_mae, label: 'Mae' %>
            <%= f.input :antec_irmaos, label: 'Irmãos' %>
            <%= f.input :antec_conjuge, label: 'Conjuge' %>
            <%= f.input :antec_filhos, label: 'Filhos' %>
          </fieldset>

          <%= f.input :obs3, label: 'E.F.',         input_html: { :rows => '3' } %>
          <%= f.input :obs4, label: 'Conduta H.D.', input_html: { :rows => '3' } %>
          <%= f.input :obs5, label: 'Evolução',     input_html: { :rows => '10', :onfocus => 'textAreaAdjust(this)' } %>
        </fieldset>

        <div class="form-actions">
          <%= f.submit 'Salvar', :class => 'btn btn-primary' %>
          <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                      pacientes_path, :class => 'btn' %>
          <%= link_to t('.back', :default => t("helpers.links.back")),
                      pacientes_path, :class => 'btn' %>
          <%= link_to 'Visualizar', @paciente %>
        </div>
      </fieldset>
      <% end %>
    </div>
  </div>




  <!-- O codigo abaixo é para fazer campos textarea autoredimencionavel
f.input :obs3, label: 'E.F.', input_html: { :rows => '3', :onkeyup => 'textAreaAdjust(this)', :style => 'overflow:hidden' }
-->

<!-- O codigo abaixo é para fazer campos textarea autoredimencionavel -->
<script>
jQuery.each(jQuery('textarea'), function() {
    var offset = this.offsetHeight - this.clientHeight;

    var resizeTextarea = function(el) {
        jQuery(el).css('height', 'auto').css('height', el.scrollHeight + offset);
    };
    jQuery(this).on('keyup input', function() { resizeTextarea(this); }).removeAttr('data-autoresize');
});

function textAreaAdjust(o) {
    o.style.height = "1px";
    o.style.height = (25+o.scrollHeight)+"px";
}

function getIdade(dateString) {
    var today = new Date();
    var birthDate = new Date(dateString);
    var age = today.getFullYear() - birthDate.getFullYear();
    var m = today.getMonth() - birthDate.getMonth();
    if (m < 0 || (m === 0 && today.getDate() < birthDate.getDate())) {
        age--;
    }
    return age;
}

function mostra_idade(o) {
  var ida = new String;
  var data = new Date($(o).val());
  ida = getIdade(data);
  ida = ' ' + ida + ' Anos'
  $(".lado").text(ida);
  return ida
}

$(function() {
  // Códigos jQuery a serem executados quando a página carregar e correndo o risco de conflitar com outras bibliotecas JavaScript
  var data = $("#paciente_dt_nascimento");
  mostra_idade(data);
  });

</script>

app/views/pacientes/_form_c1.html.erb
<div class = "panel panel-info">
  <div class = "panel panel-heading">Dados do Paciente (<%= titulo %>)</div>

  <div class = "panel panel-body">

    <div class="container">

      <%= form_for @paciente, :html => { :class => "form-horizontal"} do |f| %>

      <%= render "shared/error_messages", :target => @paciente %>  

      <div class="form-group">
        <%= f.label 'Nome', class: "col-sm-2 control-label" %>
        <div class="col-sm-8">
          <%= f.text_field :nm_paciente, :class => "form-control input-lg" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label 'Data Nascimento', class: "col-sm-2 control-label" %>
        <div class="col-sm-3">
          <%= f.text_field :dt_nascimento, :class => "form-control"  %>
        </div>
        <%= f.label 'Estado Civil', class: "col-sm-2 control-label" %>
        <div class="col-sm-5">
          <%= f.select :estado_civil, @estado_civis, :prompt=>'Selecione...' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label 'Endereço', class: "col-sm-2 control-label" %>
        <div class="col-sm-8">
          <%= f.text_field :endereco, :class => "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label'Cidade', class: "col-sm-2 control-label" %>
        <div class="col-sm-4">
          <%= f.text_field :cidade, :class => "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label 'Profissão', class: "col-sm-2 control-label" %>
        <div class="col-sm-8">
          <%= f.text_field :profissao, :class => "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label 'Fone', class: "col-sm-2 control-label" %>
        <div class="col-sm-8">
          <%= f.text_field :fone_casa %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label 'Natural', class: "col-sm-2 control-label" %>
        <div class="col-sm-8">
          <%= f.text_field :e_mail, :class => "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label 'Primeira consulta', class: "col-sm-2 control-label" %>
        <div class="col-sm-8">
          <%= f.text_field :dt_prim_consulta %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label 'Situação', class: "col-sm-2 control-label" %>
        <div class="col-sm-8">
          <%= f.text_field :situacao %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label 'Encaminhado por', class: "col-sm-2 control-label" %>
        <div class="col-sm-8">
          <%= f.text_field :encaminhado_por, :class => "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :paciente_obs1, 'Q.P./H.P.M.A.', class: "col-sm-2 control-label" %>
        <div class="col-sm-8">
          <%= f.text_area :obs1, :size => '70x3', :title => 'Campo 1 cadastrado nos parametros', :class => "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label "paciente_obs2", 'A.P./I.D.', class: "col-sm-2 control-label" %>
        <div class="col-sm-8">
          <%= f.text_area :obs2, :cols => "200",  :rows => "3", :title => 'Campo 2 cadastrado nos parametros', :class => "form-control" %>
        </div>
      </div>

      Antecedentes Familiares
      <div class="form-group">
        <%= f.label 'Pai', class: "col-sm-2 control-label" %>
        <div class="col-sm-8">
          <%= f.text_field :antec_pai, :class => "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label 'Mãe' , class: "col-sm-2 control-label"%>
        <div class="col-sm-8">
          <%= f.text_field :antec_mae, :class => "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label 'Irmãos', class: "col-sm-2 control-label" %>
        <div class="col-sm-8">
          <%= f.text_field :antec_irmaos, :class => "form-control" %>
        </div>  
      </div>
      <div class="form-group">
        <%= f.label 'Cônjuge', class: "col-sm-2 control-label" %>
        <div class="col-sm-8">
          <%= f.text_field :antec_conjuge, :class => "form-control" %>
        </div>
      </div>      
      <div class="form-group">
        <%= f.label 'Filhos', class: "col-sm-2 control-label" %>
        <div class="col-sm-8">
          <%= f.text_field :antec_filhos, :class => "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label "paciente_obs3",'E.F', class: "col-sm-2 control-label" %>
        <div class="col-sm-8">
          <%= f.text_area :obs3, :size => '70x3', :title => 'Campo 3 cadastrado nos paramentros', :class => "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label "paciente_obs4", 'Conduta H.D.', class: "col-sm-2 control-label" %>
        <div class="col-sm-8">
          <%= f.text_area :obs4, :size => '70x3', :title => 'Campo 4 cadastrado nos parametros', :class => "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label 'Evolução', class: "col-sm-2 control-label" %>
        <div class="col-sm-8">
          <%= f.text_area :obs5, :size => '70x15', :title => 'Campo 5 cadastrado nos parametros', :class => "form-control" %>
        </div>
      </div>

      <div class="form-actions">
        <%= f.submit nil, :class => 'btn btn-primary' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                    pacientes_path, :class => 'btn' %>
      </div>
      <% end %>
    </div>  
  </div>
</div>

app/views/pacientes/edit.html.erb
<%= render :partial => "form", :locals => { :titulo => 'Editando', :nome_botao => 'Gravar Alteração'} %>

app/views/pacientes/index.html.erb
<%- model_class = Paciente -%>

<fieldset class='caixa'>
  <legend class='caixa'><%=t '.title', :default => model_class.model_name.human.pluralize.titleize  %> (<%= @totalpacientes %>)</legend>
 
<%= will_paginate @pacientes, renderer: BootstrapPagination::Rails %>
<br>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_paciente_path,
            :class => 'btn btn-primary' %>


<table class="table table-striped">

  <tbody>
    <% for paciente in @pacientes %>
      <tr>
        <td><%= link_to paciente.nm_paciente, edit_paciente_path(paciente) %></td>

        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
              paciente_path(paciente), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              paciente_path(paciente),
              :method => :delete,
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_paciente_path,
            :class => 'btn btn-primary' %>
</fieldset>

app/views/pacientes/new.html.erb
<%= render :partial => "form", :locals => { :titulo => 'Inserindo', :nome_botao => 'Gravar'} %>

app/views/pacientes/show.html.erb
<%- model_class = Medicamento -%>

<fieldset class='caixa'>
  <legend class='caixa'>Paciente</legend>

  <dl class="dl-horizontal">
    <dt></dt>
    <dd><h2><%=t '.title', :default => @paciente.nm_paciente %></h2></dd>

    <dt><strong><%= model_class.human_attribute_name("Data nascimento") %>:</strong></dt>
    <dd><%= @paciente.dt_nascimento %> - <%= @paciente.idade %></dd>

    <% unless @paciente.estado_civil.blank? %>
    <dt><strong>Estado Civil:</strong></dt>
    <dd><%= @paciente.estado_civil %></dd>
    <% end %>

    <dt><strong>Endereço:</strong></dt>
    <dd><%= @paciente.endereco %> -
        <%= @paciente.cidade.to_s %>
    </dd>

    <dt><strong>Profissão/Empresa:</strong></dt>
    <dd><%= @paciente.profissao %> -
        <%= @paciente.empresa %>
    </dd>

    <dt><strong>Fone:</strong></dt>
    <dd><%= @paciente.fone_casa %>&nbsp;
        <%= @paciente.fone_empresa %>&nbsp;
        <%= @paciente.celular %>
    </dd>

    <% unless @paciente.e_mail.blank? %>
      <dt><strong>Natural:</strong></dt>
      <dd><%= @paciente.e_mail %></dd>
    <% end %>

    <dt><strong>Primeira consulta:</strong></dt>
    <dd><%= @paciente.dt_prim_consulta %></dd>

    <dt><strong>Ultima consulta:</strong></dt>
    <dd><%= @paciente.dt_ult_consulta %></dd>

    <% unless @paciente.situacao.blank? %>
      <dt><strong>Situação:</strong></dt>
      <dd><%= @paciente.situacao %></dd>
    <% end %>

    <% unless @paciente.encaminhado_por.blank? %>
      <dt><strong>Encaminhado por:</strong></dt>
      <dd><%= @paciente.encaminhado_por %></dd>
    <% end %>


    <p><dt></dt><dd><h3>ANAMNESE</h3></dd>

    <% unless @paciente.obs1.blank? %>
      <dt><strong>Q.P./H.P.M.A.:</strong></dt>
      <dd><%= @paciente.obs1 %></dd>
    <% end %>

    <% unless @paciente.obs2.blank? %>
      <dt><strong>A.P./I.D.:</strong></dt>
      <dd><%= @paciente.obs2 %></dd>
    <% end %>

    <% unless @paciente.antec_mae.blank? %>
      <dt><strong>Antec.mãe:</strong></dt>
      <dd><%= @paciente.antec_mae %></dd>
    <% end %>

    <% unless @paciente.antec_pai.blank? %>
      <dt><strong>Antec.pai:</strong></dt>
      <dd><%= @paciente.antec_pai %></dd>
    <% end %>

    <% unless @paciente.antec_filhos.blank? %>
      <dt><strong>Antec.filhos:</strong></dt>
      <dd><%= @paciente.antec_filhos %></dd>
    <% end %>

    <% unless @paciente.antec_irmaos.blank? %>
      <dt><strong>Antec.irmãos:</strong></dt>
      <dd><%= @paciente.antec_irmaos %></dd>
    <% end %>

    <% unless @paciente.antec_conjuge.blank? %>
      <dt><strong>Antec.cônjuge:</strong></dt>
      <dd><%= @paciente.antec_conjuge %></dd>
    <% end %>

    <% unless @paciente.obs3.blank? %>
      <dt><strong>E.F.:</strong></dt>
      <dd><%= @paciente.obs3 %></dd>
    <% end %>

    <% unless @paciente.obs4.blank? %>
      <dt><strong>Conduta H.D.:</strong></dt>
      <dd><%= @paciente.obs4 %></dd>
    <% end %>

    <% unless @paciente.obs5.blank? %>
      <dt><strong>Evolução:</strong></dt>
      <dd><%= @paciente.obs5 %></dd>
    <% end %>

  </dl>

  <fieldset class='caixa'>
    <legend class='caixa'>Receitas</legend>

    <table class="table table-striped">
      <% @paciente.receitas.each do |r| %>
      <tr>
        <th><%= r.data %>&nbsp;
          <%= link_to t('.show', :default => t("helpers.links.show")),
            paciente_receita_path(@paciente, r), :class => 'btn btn-xs btn-warning glyphicon glyphicon-eye-open' %>
        </th>
        <td>
        <% r.receitais.each do |i| %>
        <%= i.medicamento.try(:descricao).to_s + ' ' + i.dose + '(' + i.qtde.to_s + ')' %>
        <br>
        <% end %>
        </td>
      </tr>
    <% end %>
    </table>

  </fieldset>

  <fieldset class='caixa'>
    <legend class='caixa'>Exames Solicitados</legend>

    <table class="table table-striped">
    <% @paciente.solexames.each do |r| %>
      <tr>
        <th><%= r.data %>
          <%= link_to t('.show', :default => t("helpers.links.show")),
            solexame_path(r, :paciente => @paciente), :class => 'btn btn-xs btn-warning glyphicon glyphicon-eye-open' %>
        </th>
        <td>
        <% r.solexameis.each do |i| %>
        <%= i.exame.descricao %>
        <br>
        <% end %>
        </td>
      </tr>
    <% end %>
    </table>
  </fieldset>

  <div class="form-actions">
    <%= link_to t('.back', :default => t("helpers.links.back")),
                pacientes_path, :class => 'btn'  %>
    <%= link_to t('.edit', :default => "Editar Paciente"),
                edit_paciente_path(@paciente), :class => 'btn btn-primary' %>
    <%= link_to t('.destroy', :default => "Excluir Paciente"),
                paciente_path(@paciente),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Você tem certeja que quer excluir toda o cadastro e a história do paciente?')) },
                :class => 'btn btn-danger' %>
    <%= link_to 'Prescrever Receita', 
                new_paciente_receita_path( @paciente ), :class => "btn btn-info" %> 
    <%= link_to 'Solicitar de Exame', 
                new_solexame_path( :paciente => @paciente ), :class => "btn btn-info" %>
  </div>  

</fieldset>