config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  devise_for :users
  resources :users

  resources :padraos

  get "welcome/index"

  resources :solexames do
    member do
      # /agreements/:id/export
      get 'export'
    end
  end

  resources :clilabs
  resources :exames
  resources :medicamentos do
    get :autocomplete_medicamento_descricao, :on => :collection
  end
  resources :viaaplics
  #resources :pacientes, :has_many => :receitas 
  resources :pacientes do
    resources :receitas 
  end
  resources :receitas do
    resources :receitais
  end

  resources :impreceita
  resources :impsolexame

  root 'welcome#index'

end

app/models/medicamento.rb
class Medicamento < ActiveRecord::Base
  belongs_to :viaaplic

  def to_s
    descricao
  end
  
end

app/controllers/medicamentos_controller.rb
class MedicamentosController < ApplicationController

  before_filter :ler_viaaplic, :only => [:new, :create, :edit, :update]
  before_action :set_medicamento, only: [:show, :edit, :update, :destroy]

  add_breadcrumb "Home" , :root_path
  add_breadcrumb "Medicamento", :medicamentos_path

  autocomplete :medicamento, :descricao, { :full_model=>true }

  # GET /medicamentos
  # GET /medicamentos.xml
  def index
    @medicamentos = Medicamento.all
  end

  # GET /medicamentos/1
  # GET /medicamentos/1.xml
  def show
    add_breadcrumb "show", medicamentos_path, :title => "Volta para o index"
  end

  # GET /medicamentos/new
  # GET /medicamentos/new.xml
  def new
    @medicamento = Medicamento.new
    add_breadcrumb "novo", medicamentos_path, :title => "Volta para o index"
  end

  # GET /medicamentos/1/edit
  def edit
    add_breadcrumb "edit", medicamentos_path, :title => "Volta para o index"
  end

  # POST /medicamentos
  # POST /medicamentos.xml
  def create
    @medicamento = Medicamento.new(medicamento_params)

    respond_to do |format|
      if @medicamento.save
        format.html { redirect_to @medicamento, notice: 'Medicamento was successfully created.' }
        format.json { render action: 'show', status: :created, location: @medicamento }
      else
        format.html { render action: 'new' }
        format.json { render json: @medicamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /medicamentos/1
  # PUT /medicamentos/1.xml
  def update
    respond_to do |format|
      if @medicamento.update(medicamento_params)
        format.html { redirect_to @medicamento, notice: 'Medicamento was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @medicamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicamentos/1
  # DELETE /medicamentos/1.xml
  def destroy
    @medicamento.destroy
    respond_to do |format|
      format.html { redirect_to medicamentos_url }
      format.json { head :no_content }
    end
  end

  protected
    def ler_viaaplic
      @vias = Viaaplic.all.collect {|p| [p.descricao, p.id] }
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_medicamento
      @medicamento = Medicamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medicamento_params
      params.require(:medicamento).permit(:descricao, :dose, :viaaplic_id)
      #params[:viaaplic]
    end

end

app/views/medicamentos/_form.html.erb
<%= simple_form_for @medicamento, html: { class: 'form-horizontal' },
  wrapper: :horizontal_form,
  wrapper_mappings: {
    check_boxes: :horizontal_radio_and_checkboxes,
    radio_buttons: :horizontal_radio_and_checkboxes,
    file: :horizontal_file_input,
    boolean: :horizontal_boolean
  } do |f| %>

  <fieldset class='caixa'>
    <legend class='caixa'>Medicamentos</legend>
    <%= f.input :descricao %>
    <%= f.input :dose %>

    <%= f.association :viaaplic, collection: @vias, prompt: "Altere a via" %>

    <div class="form-actions">
      <%= f.submit 'Salvar', :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  medicamentos_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/medicamentos/edit.html.erb
<%- model_class = Medicamento -%>

<%= render :partial => 'form' %>

app/views/medicamentos/index.html.erb
<%- model_class = Medicamento -%>

<fieldset class='caixa'>
  <legend class='caixa'><%=t '.title', :default => model_class.model_name.human.pluralize.titleize  %> (<%= @medicamentos.size %>)</legend>
 
<br>

<table class="table table-striped">

  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:descricao) %></th>
      <th><%= model_class.human_attribute_name(:dose) %></th>
      <th><%= model_class.human_attribute_name(:viaaplic) %></th>
      <th><%= model_class.human_attribute_name(:updated_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @medicamentos.order(:descricao).each do |medicamento| %>
      <tr>
        <td><%= link_to medicamento.id, medicamento_path(medicamento) %></td>
        <td><%= medicamento.descricao %></td>
        <td><%= medicamento.dose %></td>
        <td><%= medicamento.viaaplic.descricao %></td>
        <td><%= medicamento.updated_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_medicamento_path(medicamento), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      medicamento_path(medicamento),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_medicamento_path,
            :class => 'btn btn-primary' %>

app/views/medicamentos/new.html.erb
<%- model_class = Medicamento -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/medicamentos/show.html.erb
<%- model_class = Medicamento -%>

  <fieldset class='caixa'>
    <legend class='caixa'>Medicamentos</legend>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:descricao) %>:</strong></dt>
  <dd><%= @medicamento.descricao %></dd>
  <dt><strong><%= model_class.human_attribute_name(:dose) %>:</strong></dt>
  <dd><%= @medicamento.dose %></dd>
  <dt><strong><%= model_class.human_attribute_name(:viaaplic_id) %>:</strong></dt>
  <dd><%= @medicamento.viaaplic.descricao %></dd>
  <dt><strong><%= model_class.human_attribute_name(:created_at) %>:</strong></dt>
  <dd><%= @medicamento.created_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:updated_at) %>:</strong></dt>
  <dd><%= @medicamento.updated_at %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              medicamentos_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_medicamento_path(@medicamento), :class => 'btn btn-primary' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              medicamento_path(@medicamento),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>