config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  devise_for :users
  resources :users

  resources :padraos

  get "welcome/index"

  resources :solexames do
    member do
      # /agreements/:id/export
      get 'export'
    end
  end

  resources :clilabs
  resources :exames
  resources :medicamentos do
    get :autocomplete_medicamento_descricao, :on => :collection
  end
  resources :viaaplics
  #resources :pacientes, :has_many => :receitas 
  resources :pacientes do
    resources :receitas 
  end
  resources :receitas do
    resources :receitais
  end

  resources :impreceita
  resources :impsolexame

  root 'welcome#index'

end

app/models/clilab.rb
class Clilab < ApplicationRecord
end

app/controllers/clilabs_controller.rb
class ClilabsController < ApplicationController
  # GET /clilabs
  # GET /clilabs.xml
  def index
    @clilabs = Clilab.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @clilabs }
    end
  end

  # GET /clilabs/1
  # GET /clilabs/1.xml
  def show
    @clilab = Clilab.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @clilab }
    end
  end

  # GET /clilabs/new
  # GET /clilabs/new.xml
  def new
    @clilab = Clilab.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @clilab }
    end
  end

  # GET /clilabs/1/edit
  def edit
    @clilab = Clilab.find(params[:id])
  end

  # POST /clilabs
  # POST /clilabs.xml
  def create
    @clilab = Clilab.new(params[:clilab])

    respond_to do |format|
      if @clilab.save
        flash[:notice] = 'Clilab was successfully created.'
        format.html { redirect_to(@clilab) }
        format.xml  { render :xml => @clilab, :status => :created, :location => @clilab }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @clilab.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /clilabs/1
  # PUT /clilabs/1.xml
  def update
    @clilab = Clilab.find(params[:id])

    respond_to do |format|
      if @clilab.update_attributes(params[:clilab])
        flash[:notice] = 'Clilab was successfully updated.'
        format.html { redirect_to(@clilab) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @clilab.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /clilabs/1
  # DELETE /clilabs/1.xml
  def destroy
    @clilab = Clilab.find(params[:id])
    @clilab.destroy

    respond_to do |format|
      format.html { redirect_to(clilabs_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/clilabs/_form.html.erb
<% form_for(@clilab) do |f| %>
  <%= render "shared/error_messages", :target => @clilab %>  

  <div class="field">
    <%= f.label 'Nome' %><br />
    <%= f.text_field :nm %>
  </div>

  <div class="actions">
    <%= f.submit nome_botao %>
  </div>
<% end %>

<%= link_to 'Mostrar', @clilab %> |
<%= link_to 'Voltar', clilabs_path %>

  

app/views/clilabs/edit.html.erb
<%- model_class = Laboratorio -%>

<%= render :partial => "form", :locals => { :titulo => 'Alterando', :nome_botao => 'Gravar Alterações'} %>

app/views/clilabs/index.html.erb
<h1>Lista clínicas e laboratórios</h1>

<table>
  <tr>
    <th>Nome Clínica/Laboratório</th>
  </tr>

<% for clilab in @clilabs %>
  <tr>
    <td><%=h clilab.nm %></td>
    <td><%= link_to 'Mostrar', clilab %></td>
    <td><%= link_to 'Alterar', edit_clilab_path(clilab) %></td>
    <td><%= link_to 'Excluir', clilab, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Novo registro', new_clilab_path %>

app/views/clilabs/new.html.erb
<%= render :partial => "form", :locals => { :titulo => 'Novo', :nome_botao => 'Gravar' } %>

app/views/clilabs/show.html.erb
<p>
  <b>Nome Clinica/Laboratorio:</b>
  <%=h @clilab.nm %>
</p>


<%= link_to 'Edit', edit_clilab_path(@clilab) %> |
<%= link_to 'Back', clilabs_path %>