config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  devise_for :users
  resources :users

  resources :padraos

  get "welcome/index"

  resources :solexames do
    member do
      # /agreements/:id/export
      get 'export'
    end
  end

  resources :clilabs
  resources :exames
  resources :medicamentos do
    get :autocomplete_medicamento_descricao, :on => :collection
  end
  resources :viaaplics
  #resources :pacientes, :has_many => :receitas 
  resources :pacientes do
    resources :receitas 
  end
  resources :receitas do
    resources :receitais
  end

  resources :impreceita
  resources :impsolexame

  root 'welcome#index'

end

app/models/exame.rb
class Exame < ApplicationRecord
end

app/controllers/exames_controller.rb
class ExamesController < ApplicationController

  before_action :set_exame, only: [:show, :edit, :update, :destroy]

  add_breadcrumb "Home" , :root_path
  add_breadcrumb "Exames", :exames_path

    # GET /exames
  # GET /exames.xml
  def index
    @exames = Exame.all
  end

  # GET /exames/1
  # GET /exames/1.xml
  def show
    add_breadcrumb "show", exames_path, :title => "Volta para o index"
  end

  # GET /exames/new
  # GET /exames/new.xml
  def new
    @exame = Exame.new
    add_breadcrumb "novo", exames_path, :title => "Volta para o index"
  end

  # GET /exames/1/edit
  def edit
    add_breadcrumb "edit", exames_path, :title => "Volta para o index"
  end

  # POST /exames
  # POST /exames.xml
  def create
    @exame = Exame.new(exame_params)

    respond_to do |format|
      if @exame.save
        format.html { redirect_to @exame, notice: 'Exame foi criado com sucesso.' }
        format.json { render action: 'show', status: :created, location: @exame }
      else
        format.html { render action: 'new' }
        format.json { render json: @exame.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /exames/1
  # PUT /exames/1.xml
  def update
   respond_to do |format|
      if @exame.update(exame_params)
        format.html { redirect_to @exame, notice: 'Exame foi gravado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @exame.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exames/1
  # DELETE /exames/1.xml
 def destroy
    @exame.destroy
    respond_to do |format|
      format.html { redirect_to exames_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exame
      @exame = Exame.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exame_params
      params.require(:exame).permit(:descricao)
      #params[:exame]
    end
end

app/views/exames/_form.html.erb
<%= simple_form_for @exame, html: { class: 'form-horizontal' },
  wrapper: :horizontal_form,
  wrapper_mappings: {
    check_boxes: :horizontal_radio_and_checkboxes,
    radio_buttons: :horizontal_radio_and_checkboxes,
    file: :horizontal_file_input,
    boolean: :horizontal_boolean
  } do |f| %>

  <fieldset class='caixa'>
    <legend class='caixa'>Exames</legend>

    <%= f.input :descricao %>

    <div class="form-actions">
      <%= f.submit 'Salvar', :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                exames_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/exames/edit.html.erb
<%- model_class = Exame -%>

<%= render :partial => 'form' %>

app/views/exames/index.html.erb
<%- model_class = Exame -%>

<fieldset class='caixa'>
  <legend class='caixa'><%=t '.title', :default => model_class.model_name.human.pluralize.titleize  %> (<%= @exames.size %>)</legend>
<br>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:descricao) %></th>
      <th><%= model_class.human_attribute_name(:updated_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @exames.each do |exame| %>
      <tr>
        <td><%= link_to exame.id, exame_path(exame) %></td>
        <td><%= exame.descricao %></td>
        <td><%= exame.updated_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_exame_path(exame), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      exame_path(exame),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_exame_path,
            :class => 'btn btn-primary' %>

app/views/exames/new.html.erb
<%- model_class = Exame -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/exames/show.html.erb
<%- model_class = Exame -%>

  <fieldset class='caixa'>
    <legend class='caixa'>Exames</legend>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:descricao) %>:</strong></dt>
  <dd><%= @exame.descricao %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              exames_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_exame_path(@exame), :class => 'btn btn-primary' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              exame_path(@exame),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>
</fieldset>